language: python
os: linux

python:
  - "3.6"
  - "nightly"

before_script:
  - ln -s conftest conftest.py

install:
  - "pip install -r requirements.txt"
  - "python -m nltk.downloader punkt"
  - "python -m nltk.downloader stopwords"

script:
  - pytest
